---
title: 关于5G的看法😊
author: linxi
date: '2019-06-13'
slug: write
categories:
  - R
tags: []
---
## 什么是5G？比4G多1G吗😀
5G网络（5G Network）是第五代移动通信网络，其峰值理论传输速度可达每8秒1GB，比4G网络的传输速度快数百倍。举例来说，一部1G的电影可在8秒之内下载完成。随着5G技术的诞生，用智能终端分享3D电影、游戏以及超高画质（UHD）节目的时代正向我们走来。5G不仅可以创造巨大的利润，还可以改变我们的生活方式。在5G时代我们可以实现真正的万物互联（看得我热血沸腾了）。

## 5G对我们生活的影响
### 颠覆价值体系
例如，5G低延时的特征使无人驾驶成为可能，按需使用、随用随租的共享经济或将取代传统的汽车购买、使用模式，整车制造厂商的重要性下降，无人驾驶平台的重要性凸显，娱乐、办公等车载增值服务将不断涌现。

### 提升生产效率
例如，借助5G技术实现万物互联，以智能工厂为代表的生产系统将能够随时随地感知零部件、设备、产品的位置和状态，及时进行零部件的传递、派单生产和产品交付，同时进行实时设备监控、产品运营状态运维、保养等服务。

### 促进技术创新
例如，万物互联后将产生更多的数据，使受制于数据规模而发展缓慢的一些人工智能模型获得优化，促进人工智能应用的发展；虚拟现实技术使得产品的开发、设计更加高效、直观。

此外，由于5G时代万物互联成为可能，生产设备、家居、车辆、基础设施、公共服务等将都被网络连接起来，因此5G成为关系人身安全、生产安全、经济安全、国防安全的重要支撑。

## 中国5G水平
中国国内具备支持5G发展的有利条件。

#### 第一
中国是世界人口最多的国家和世界第二大经济体，消费者和企业用户数量庞大，能够为5G以及下游应用产业的发展提供足够规模的市场，对5G相关企业的投资具有吸引力；同时，规模经济带来的低成本又会吸引用户，从而进一步扩大市场规模，形成正反馈的促进机制。

#### 第二
中国已经形成由电信运营商、设备制造商、零部件供应商、下游应用提供商等组成的较为完善的移动通信生态。完善的产业生态不但能够降低5G投资风险，而且能够形成合力，加速5G技术的突破和商业化应用。

#### 第三
中国4G成熟度高，拥有世界上最大、覆盖最广、品质最高的4G网络，中国4G基站数占全世界4G基站数的60%。4G网络中的铁塔、电源、传输光缆、机房配套设备等均可以用于5G，有利于5G网络的大规模建设。

#### 第四
中国拥有世界上最齐全的产业门类、最完整的产业链和最完善的产业配套体系，拥有丰富的应用场景，为孕育创新性的5G下游应用提供了市场基础。

#### 第五
经过近20年消费互联网的高速发展，中国形成了以BAT为代表的一批世界知名的领军型互联网企业，这些企业既积累了丰富的数据资源，又拥有强大的算力、算法和技术创新能力，目前正在积极进入物联网、车联网等产业互联网领域，将成为推动5G下游应用发展的重要力量。